sudo: false
language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: hhvm
  allow_failures:
  - php: hhvm

before_install:
- openssl aes-256-cbc -K $encrypted_7f463b6b860b_key -iv $encrypted_7f463b6b860b_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- phpenv config-rm xdebug.ini
- composer self-update

install:
- travis_retry composer install --no-interaction
- composer info -i

before_script:
 - chmod +x ./bin/deploy.sh
 
script:
- phpunit -c ./tests/phpunit.xml


after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi
