language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.1

before_install:
  - travis_retry composer self-update

script:
  - phpunit -c ./tests/phpunit.xml

before_deploy:
  - composer buildphar

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - build/PhpWrapperProffix.phar
  skip_cleanup: true
  on:
    tags: false
    php: 5.6
